name: Build & Deploy to Aliyun
on:
  # 手动触发工作流
  workflow_dispatch:
  # 以下为push后自动触发，如需要请参考下面配置
  # push: 
  #   branches: [main]
  #   paths-ignore:
  #     - '*.md'
  #     - 'nodemon.json'
  #     - '.gitignore'
  #     - '.babelrc'

jobs:
  xysbtn-upload-build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: xysbtn-upload docker run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.PRAVITE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~ && \
            echo "开始克隆" && \
            git clone ${{ vars.REPO }} xysbtn-upload && \
            cd xysbtn-upload && \
            echo "暂定已运行的容器" && \
            docker-compose down && \
            echo "删除过时的镜像" && \
            docker rmi xysbtn-upload && \
            echo "开始build新镜像" && \
            docker-compose up -d && \
            echo "开始清理克隆的仓库" && \
            cd ~ && \
            rm -rf xysbtn-upload
          